In [1]:
import numpy as np

In [2]:
simple_list = [6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr = np.array([6,7,9])
arr

array([6, 7, 9])

In [4]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [6]:
np.arange(10,83,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [14]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
np.random.rand(2,4)

array([[0.22317365, 0.54270314, 0.75370827, 0.72738949],
       [0.90090865, 0.35776828, 0.18188894, 0.20554669]])

In [19]:
np.random.randn(2,4)

array([[-0.01227952,  1.27022272,  0.71870017,  0.42505896],
       [ 0.25430655, -0.3166472 , -3.00363625,  0.41657577]])

In [21]:
np.random.randint(0,11,30)

array([ 5,  8,  6,  4,  7,  7,  0,  0, 10,  7,  1,  8,  5,  2,  8,  3,  3,
        1,  4,  9,  1,  5,  5,  4,  3,  1,  8,  8,  0,  0])