# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [2]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [9]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [12]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(2,4)

array([[0.08171465, 0.672569  , 0.87450218, 0.373254  ],
       [0.00171456, 0.43994819, 0.69877799, 0.62564328]])

In [20]:
np.random.rand(2,7)

array([[0.75129057, 0.96431837, 0.05737721, 0.422968  , 0.60551908,
        0.14944086, 0.54568809],
       [0.79685889, 0.1701854 , 0.25052217, 0.29656567, 0.13917433,
        0.36679151, 0.83768996]])

In [27]:
np.random.randint(2,10)

4

In [28]:
np.random.randint(20,56,100)

array([23, 28, 32, 53, 30, 22, 52, 36, 54, 23, 35, 49, 41, 27, 46, 54, 45,
       49, 52, 44, 47, 34, 44, 40, 20, 24, 39, 51, 23, 47, 33, 52, 27, 40,
       25, 44, 31, 53, 25, 38, 33, 55, 39, 39, 49, 26, 39, 24, 46, 55, 22,
       35, 35, 25, 47, 48, 30, 54, 41, 30, 50, 22, 48, 52, 22, 40, 37, 33,
       40, 48, 35, 25, 31, 50, 30, 30, 49, 28, 25, 33, 34, 49, 36, 30, 35,
       23, 28, 27, 52, 39, 31, 43, 49, 42, 43, 34, 38, 50, 36, 28])

In [29]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
rand_array=np.random.randint(0,100,20)
rand_array

array([71, 16, 70, 23, 44, 19, 30, 53,  1, 39, 25, 99, 43, 93, 72, 37, 40,
       47, 92, 68])

In [34]:
sample_array.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [39]:
rand_array.min()

1

In [40]:
rand_array.argmin()

8

In [ ]:
sample_array

In [ ]:
sample_array.shape

In [ ]:
sample_array.reshape(5,6)

In [41]:
sample_array.dtype

dtype('int32')

In [42]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
a=np.random.rand(2,3)
a

array([[0.04783059, 0.88932134, 0.49058278],
       [0.02460932, 0.16868764, 0.35565931]])

In [45]:
a.T

array([[0.04783059, 0.02460932],
       [0.88932134, 0.16868764],
       [0.49058278, 0.35565931]])

In [ ]:
import numpy as np

In [47]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
sample_array[8]

18

In [49]:
sample_array[2:5]

array([12, 13, 14])

In [50]:
sample_array[[2,5]]

array([12, 15])

In [51]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [52]:
sample_array=np.arange(10,21)
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [53]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [54]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional array

In [55]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [56]:
sample_matrix[0][2]

1

In [57]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [58]:
sample_matrix[2]

array([56, 76, 24,  7])

### Custom indexing

In [59]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [62]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 32],
       [ 7, 24]])

###  Selection techniques

In [63]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [64]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [65]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [67]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [70]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [71]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [72]:
np.max(sample_array)

30

In [73]:
np.min(sample_array)

1

In [74]:
np.argmax(sample_array)

29

In [75]:
np.argmin(sample_array)

0

In [76]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [77]:
np.std(sample_array)

8.65544144839919

In [78]:
np.var(sample_array)


74.91666666666667

In [79]:
np.mean(sample_array)

15.5

In [80]:
array=np.random.randn(3,6)
array

array([[ 0.7604834 ,  1.21615337, -0.04736615,  0.35698434, -1.00698652,
         0.7861304 ],
       [-0.13757089,  1.15287055, -1.15676092, -2.56742728, -0.09636349,
        -1.17173119],
       [-0.45438789, -1.61487419, -2.79171672, -0.11951588, -1.44307974,
         1.1960022 ]])

In [81]:
np.round(array,decimals=2)

array([[ 0.76,  1.22, -0.05,  0.36, -1.01,  0.79],
       [-0.14,  1.15, -1.16, -2.57, -0.1 , -1.17],
       [-0.45, -1.61, -2.79, -0.12, -1.44,  1.2 ]])

In [82]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [83]:
import pandas as pd

In [84]:
labels=['w','x','y','z']
list=[10,20,30,40]
array=np.array([10,20,30,40])
dict={'w':10,'x':20,'y':30,'z':40}


In [87]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [88]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [89]:
pd.Series(array,labels)

w    10
x    20
y    30
z    40
dtype: int32

In [90]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [91]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [92]:
sports1['cricket']

1

In [93]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [94]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [103]:
df1=pd.DataFrame(np.random.randn(8,5),index='A B C D E F G H '.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1


Score1    Score2    Score3    Score4    Score5
A  1.120633  0.121502  0.114278 -0.545232  0.458524
B -1.971300  0.694882  0.030918 -1.435101 -1.394730
C  1.410554 -1.271082 -1.115625 -1.600306 -0.233356
D -1.642979  0.378120 -2.482190  0.337027  0.095041
E  1.619196  0.601985  0.844454 -0.771232  0.240528
F  0.020262 -0.119882  1.363250  0.016229 -0.189975
G  0.531611  1.301073  0.112408 -1.480927  1.255575
H  0.103865 -1.191244  0.180627 -1.061857 -0.898839

In [104]:
df1['Score2']

A    0.121502
B    0.694882
C   -1.271082
D    0.378120
E    0.601985
F   -0.119882
G    1.301073
H   -1.191244
Name: Score2, dtype: float64

In [105]:
df1[['Score2','Score1']]


Score2    Score1
A  0.121502  1.120633
B  0.694882 -1.971300
C -1.271082  1.410554
D  0.378120 -1.642979
E  0.601985  1.619196
F -0.119882  0.020262
G  1.301073  0.531611
H -1.191244  0.103865

In [108]:

df1['Score6']=df1['Score1']+df1['Score2']
df1



Score1    Score2    Score3    Score4    Score5    Score6
A  1.120633  0.121502  0.114278 -0.545232  0.458524  1.242136
B -1.971300  0.694882  0.030918 -1.435101 -1.394730 -1.276418
C  1.410554 -1.271082 -1.115625 -1.600306 -0.233356  0.139471
D -1.642979  0.378120 -2.482190  0.337027  0.095041 -1.264860
E  1.619196  0.601985  0.844454 -0.771232  0.240528  2.221181
F  0.020262 -0.119882  1.363250  0.016229 -0.189975 -0.099620
G  0.531611  1.301073  0.112408 -1.480927  1.255575  1.832684
H  0.103865 -1.191244  0.180627 -1.061857 -0.898839 -1.087378

In [114]:
df1.drop()



Score1    Score2    Score3    Score4    Score5    Score6
B -1.971300  0.694882  0.030918 -1.435101 -1.394730 -1.276418
C  1.410554 -1.271082 -1.115625 -1.600306 -0.233356  0.139471
D -1.642979  0.378120 -2.482190  0.337027  0.095041 -1.264860
E  1.619196  0.601985  0.844454 -0.771232  0.240528  2.221181
F  0.020262 -0.119882  1.363250  0.016229 -0.189975 -0.099620
G  0.531611  1.301073  0.112408 -1.480927  1.255575  1.832684
H  0.103865 -1.191244  0.180627 -1.061857 -0.898839 -1.087378

In [115]:
df1.reset_index()



index    Score1    Score2    Score3    Score4    Score5    Score6
0     A  1.120633  0.121502  0.114278 -0.545232  0.458524  1.242136
1     B -1.971300  0.694882  0.030918 -1.435101 -1.394730 -1.276418
2     C  1.410554 -1.271082 -1.115625 -1.600306 -0.233356  0.139471
3     D -1.642979  0.378120 -2.482190  0.337027  0.095041 -1.264860
4     E  1.619196  0.601985  0.844454 -0.771232  0.240528  2.221181
5     F  0.020262 -0.119882  1.363250  0.016229 -0.189975 -0.099620
6     G  0.531611  1.301073  0.112408 -1.480927  1.255575  1.832684
7     H  0.103865 -1.191244  0.180627 -1.061857 -0.898839 -1.087378

In [116]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123